spring.application.name=customer360-backend
server.port=8080

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

ai.summary.enabled=true
ai.ollama.url=http://localhost:11434/api/generate
ai.ollama.model=llama3.2